[project]
name = "somesy"
version = "0.7.3"
description = "A CLI tool for synchronizing software project metadata."
keywords = ["metadata", "FAIR"]
license = "MIT"
repository = "https://github.com/Materials-Data-Science-and-Informatics/somesy"
homepage = "https://materials-data-science-and-informatics.github.io/somesy"
documentation = "https://materials-data-science-and-informatics.github.io/somesy"

[[project.people]]
family-names = "Soylu"
given-names = "Mustafa"
email = "m.soylu@fz-juelich.de"
orcid = "0000-0003-2637-0432"

contribution = "Main developer, maintainer and tester."
contribution_begin = "2023-03-01"
contribution_types = ["maintenance", "code", "test", "review", "doc"]

author = true
maintainer = true

[[project.people]]
family-names = "Pirogov"
given-names = "Anton"
email = "a.pirogov@fz-juelich.de"
orcid = "0000-0002-5077-7497"

contribution = "Concepts, tool development and enhancement, documentation."
contribution_begin = "2023-03-01"
contribution_end = "2023-04-30"
contribution_types = ["ideas", "code", "test", "review", "doc"]

author = true

[[project.people]]
family-names = "Br√∂der"
given-names = "Jens"
email = "j.broeder@fz-juelich.de"
orcid = "0000-0001-7939-226X"

contribution = "Discussions and suggestions concerning metadata standards and usability."
contribution_begin = "2023-03-01"
contribution_end = "2023-03-31"
contribution_types = ["ideas"]

[[project.people]]
family-names = "Hofmann"
given-names = "Volker"
email = "v.hofmann@fz-juelich.de"
orcid = "0000-0002-5149-603X"

contribution = "Discussions and suggestions concerning tool scope and usability."
contribution_begin = "2023-06-01"
contribution_end = "2023-06-30"
contribution_types = ["ideas", "doc"]

publication_author = true

[[project.people]]
family-names = "Sandfeld"
given-names = "Stefan"
email = "s.sandfeld@fz-juelich.de"
orcid = "0000-0001-9560-4728"

contribution_types = ["fundingFinding"]

publication_author = true
